name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.schoolproject
depend: [LibsDisguises,ProtocolLib]
commands:
  startdisguise:
    description: Starts Diguise Plugin
    usage: /startdisguise
    permission: schoolproject.start